language: node_js

node_js:
  - '13' # use nodejs v10 LTS

before_install:
  - npm install -g yarn

install:
  - yarn install

cache:
  yarn: true
  directories:
    - .yarn

before_script:
  - yarn add global gatsby-cli

deploy:
  provider: script
  script: yarn install && yarn run deploy # generate static files
  skip-cleanup: true
  github-token: $GH_TOKEN
  on:
    branch: source

branches:
  only:
    - source # build source branch only

